name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t sam6569/ci-cd-demo:latest .
          docker push sam6569/ci-cd-demo:latest

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add EC2 server to known hosts
        run: ssh-keyscan -H 13.53.49.194 >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh ec2-user@13.53.49.194 "
            docker pull sam6569/ci-cd-demo:latest &&
            docker stop app || true &&
            docker rm app || true &&
            docker run -d --name app -p 80:3000 sam6569/ci-cd-demo:latest
          "
